### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by denny0810** [AnotiaWang/gh-proxy-go#1]
I'm encountering the issue below while using the docker version. 
Server error: Get "https://raw.githubusercontent.com/xxxxxxxxxx": dial tcp: lookup raw.githubusercontent.com on 127.0.0.11:53: server misbehaving
Could you help to tell how to solve it?

**Comment by AnotiaWang** [comment]
Looks fine from my side. Can you provide a screenshot, or the URL that can trigger this issue?

<img width="1185" alt="截屏2024-07-25 17 31 30" src="https://github.com/user-attachments/assets/b50f8f7b-0385-4c86-a29d-86eeb806c1af">

**Comment by AnotiaWang** [comment]
The error "server misbehaving" could come from the DNS server. You can try changing your DNS.

**Comment by denny0810** [comment]
It's working now after reinstall the system.
